### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by Fang-Haoshu** [radmahdi/BB8#4]
Hi Mahdi! I am very interested in this project. Will the code still be publicly available?  Thanks a lot in advance!

**Comment by XuankeShi** [comment]
Hi Mahdi! I am very interested in this project too. Will the code still be publicly available?

**Comment by SimonvanEeden** [comment]
I have had email contact with Mahdi Rad, and he said he cannot make the code publicly available because of IP issues. Sorry guys.
